# Amaidesu STT Plugin Configuration: src/plugins/stt/config.toml
# -*- coding: utf-8 -*-

[iflytek_asr]
# 讯飞开放平台 ASR 配置
host = "iat-api.xfyun.cn"      # Spark Domain v3.5
path = "/v2/iat"               # API Path
appid = "YOUR_APPID"           # 你的 APPID
api_key = "YOUR_API_KEY"       # 你的 API Key
api_secret = "YOUR_API_SECRET" # 你的 API Secret

[vad]
# 语音活动检测 (VAD) 配置
enable = true             # 是否启用 VAD
silence_seconds = 1.0     # 判定为静音的阈值 (秒)
max_record_seconds = 15.0 # 单个语音片段的最大录制时长 (秒)
# vad_threshold = 0.5      # Silero VAD 灵敏度阈值 (0-1, 越高越不灵敏)

[audio]
# 音频输入配置
sample_rate = 16000 # 采样率 (讯飞要求 16000 或 8000)
channels = 1        # 声道数 (讯飞要求单声道)
dtype = "int16"     # 音频数据类型 (讯飞要求 PCM 16bit)
# 指定输入音频设备名称 (留空或注释掉以使用系统默认设备)
# stt_input_device_name = ""
stt_input_device_name = ""

# --- STT Correction Configuration ---
# 是否在发送给 MaiCore 前尝试使用 stt_correction 服务修正结果
enable_correction = true

# --- Message Sending Configuration ---
# 配置发送给 MaiCore 的消息结构

[message_config]
# 用户信息 (可以和控制台不同)
user_id = 1
user_nickname = "语音输入"
user_cardname = "admin" # 可以留空 ""

# 群组信息 (使用和控制台一样的私聊)
enable_group_info = false
group_id = 0
group_name = "test"

# 格式信息
# content_format: STT 发送的消息主要是文本
content_format = ["text"]
# accept_format: 期望 MaiCore 回复中可能包含什么类型 (与控制台对齐)
accept_format = ["text"] # 扩展以匹配模板示例

# 模板信息
enable_template_info = true
template_name = "stt"
template_default = false

# 模板内容 (通常为空，除非 STT 需要特定模板)
[message_config.template_items]
reasoning_prompt_main = '''
{relation_prompt_all}
{memory_prompt}
{prompt_info}
{schedule_prompt}
{chat_target}
{chat_talking_prompt}

# 角色设定
你现在扮演一位名叫{bot_name}的虚拟主播。有人也叫你{bot_other_names}，
{prompt_personality}

# 回应规则
1. 保持身份：始终以"麦麦"的身份发言。
2. 积极互动：
   - 热情回应观众的问候和提问
   - 记住并提及活跃观众的名字
   - 结合当前直播内容进行回应
3. 内容风格：
    - 简洁、生动、口语化
   - 对常见问题准备有个性的回答
4. 边界处理：
   - 巧妙回避无法回答的问题
   - 用幽默化解不友善的弹幕
   - 避免敏感话题
5. 优先级：优先回应有趣或能引发互动的话题

# 输入格式 (示例)
[用户名]: [弹幕内容]
例如：
路人甲: 主播今天状态好好！
粉丝乙: 主播玩这个游戏有什么技巧吗？

# 输出格式 (你的回应)
直接生成你的回应内容，不需要包含用户名或其他前缀。
例如 (根据上面的输入)：
"谢谢夸奖~ 今天感觉能量满满！"
这个呀，我还在摸索呢，不过感觉关键是要[分享一个简单技巧]，大家也可以试试看！

#特殊声明：admin一般为系统管理员或developer，见机行事

现在你的语音输入中，用户[{sender_name}]说的「{message_txt}」引起了你的注意。
请你根据当前的聊天主体{chat_target_2}、你的人设、以及之前的弹幕/语音记录，给出日常且口语化的、热情且符合主播身份的回复。
重要提示：你的回复应该只包含你需要直接说出口的话语。请严格避免在回复中包含任何括号 `()` `（）` `[]` `【】` 及其中的动作描述、表情、场景说明或音效提示。你的输出必须是纯粹的口语文本。
说中文，尽量不要说你说过的话。
在请你读读之前的记录，{mood_prompt}
'''

# 附加配置
# additional_config = { is_from_adapter = false, adapter_type = "amaidesu_stt", original_type = "text", interaction_mode = "direct_command", maimcore_reply_probability_gain = 1 } # 添加 maimcore_reply_probability_gain
